/* eslint-disable */

// This file was automatically generated by TanStack Router.
// It has been converted to JavaScript so the project no longer depends on
// TypeScript source files at runtime.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SplatRouteImport } from "./routes/$";
import { Route as IndexRouteImport } from "./routes/index";

const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
});

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});

const rootRouteChildren = {
  IndexRoute,
  SplatRoute,
};

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren);
